export const SERVER = 'SERVER/';

export const UPDATE_SETTINGS = 'UpdateSettings';
export const UPDATE_FOCUS_SETTING = 'UpdateFocusSetting';

export const RESET_GAME = 'RESET_GAME';
export const SET_PHASE = 'SET_PHASE';
export const ADD_CARD = 'ADD_CARD';
export const SELECT_CARD = 'SELECT_CARD';
export const SELECT_PIECE = 'SELECT_PIECE';
export const PLACE_CARD = 'PLACE_CARD';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const START_AI_TURN = 'START_AI_TURN';
export const END_AI_TURN = 'END_AI_TURN';

export const CLEAR_FORM_ERRORS = 'CLEAR_FORM_ERRORS';

export const CREATE_GAME_FAILED = 'CREATE_GAME_FAILED';
export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';

export const PASSWORD_RESET_CLEAR = 'PASSWORD_RESET_CLEAR';
export const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

export const GET_GAME_FAILED = 'GET_GAME_FAILED';
export const GET_GAME_REQUEST = 'GET_GAME_REQUEST';
export const GET_GAME_SUCCESS = 'GET_GAME_SUCCESS';

export const GET_GAMES_FAILED = 'GET_GAMES_FAILED';
export const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';

export const EMAIL_VERIFIED = 'EMAIL_VERIFIED';

export const USER_PROFILE = 'USER_PROFILE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

export const RESEND_EMAIL_VERIFICATION = 'RESEND_EMAIL_VERIFICATION';
export const RESEND_EMAIL_VERIFICATION_SUCCESS = 'RESEND_EMAIL_VERIFICATION_SUCCESS';
export const RESEND_EMAIL_VERIFICATION_FAILED = 'RESEND_EMAIL_VERIFICATION_FAILED';
export const RESEND_EMAIL_VERIFICATION_CLEAR = 'RESEND_EMAIL_VERIFICATION_CLEAR';

export const SEND_INVITE_REQUEST = 'SEND_INVITE_REQUEST';
export const SEND_INVITE_SUCCESS = 'SEND_INVITE_SUCCESS';
export const SEND_INVITE_FAILED = 'SEND_INVITE_FAILED';

export const SEND_PASSWORD_RESET = 'SEND_PASSWORD_RESET';
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';
export const SEND_PASSWORD_RESET_FAILED = 'SEND_PASSWORD_RESET_FAILED';
export const SEND_PASSWORD_RESET_CLEAR = 'SEND_PASSWORD_RESET_CLEAR';