export const UPDATE_SETTINGS = 'UpdateSettings';
export const UPDATE_FOCUS_SETTING = 'UpdateFocusSetting';

export const RESET_GAME = 'ResetGame';
export const SET_PHASE = 'SetPhase';
export const ADD_CARD = 'AddCard';
export const SELECT_CARD = 'SelectCard';
export const SELECT_PIECE = 'SelectPiece';
export const PLACE_CARD = 'PlaceCard';
export const SIGN_IN_FORM_ERROR_RESET = 'SIGN_IN_FORM_ERROR_RESET';
export const SIGN_IN_FORM_ERROR = 'SIGN_IN_FORM_ERROR';
export const SIGN_UP_FORM_ERROR = 'SIGN_UP_FORM_ERROR';
export const SIGN_UP_FORM_ERROR_RESET = 'SIGN_UP_FORM_ERROR_RESET';
export const UPDATE_BOARD = 'UpdateBoard';

export const START_AI_TURN = 'StartAITurn';
export const END_AI_TURN = 'EndAITurn';

export const CREATE_GAME_FAILED = 'CREATE_GAME_FAILED';
export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';

export const FORGOT_PASSWORD_FORM_ERROR = 'FORGOT_PASSWORD_FORM_ERROR';
export const FORGOT_PASSWORD_FORM_ERROR_RESET = 'FORGOT_PASSWORD_FORM_ERROR_RESET';

export const PASSWORD_RESET_CLEAR = 'PASSWORD_RESET_CLEAR';
export const PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

export const GET_GAMES_FAILED = 'GET_GAMES_FAILED';
export const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';

export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL';

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
export const AUTH_SIGNOUT_FAIL = 'AUTH_SIGNOUT_FAIL';

export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED';

export const USER_PROFILE = 'USER_PROFILE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

export const RESEND_EMAIL_VERIFICATION = 'RESEND_EMAIL_VERIFICATION';
export const RESEND_EMAIL_VERIFICATION_SUCCESS = 'RESEND_EMAIL_VERIFICATION_SUCCESS';
export const RESEND_EMAIL_VERIFICATION_FAILED = 'RESEND_EMAIL_VERIFICATION_FAILED';
export const RESEND_EMAIL_VERIFICATION_CLEAR = 'RESEND_EMAIL_VERIFICATION_CLEAR';

export const SEND_PASSWORD_RESET = 'SEND_PASSWORD_RESET';
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';
export const SEND_PASSWORD_RESET_FAILED = 'SEND_PASSWORD_RESET_FAILED';
export const SEND_PASSWORD_RESET_CLEAR = 'SEND_PASSWORD_RESET_CLEAR';

export const RESET_PASSWORD_FORM_ERROR = 'RESET_PASSWORD_FORM_ERROR';
export const RESET_PASSWORD_FORM_ERROR_RESET = 'RESET_PASSWORD_FORM_ERROR_RESET';