const PHASE = {
    SETTINGS_SELECTION: 'SETTINGS_SELECTION',
    INVITE: 'INVITE',
    HOLD: 'HOLD',
    HAND_SELECTION: 'HAND_SELECTION',
    CARD_SELECTION: 'CARD_SELECTION',
    PIECE_SELECTION: 'PIECE_SELECTION',
    GAME_OVER: 'GAME_OVER'
};

export default PHASE;