const PHASE = {
    SETTINGS_SELECTION: 'SETTINGS_SELECTION',
    INVITE: 'INVITE',
    HAND_SELECTION: 'HAND_SELECTION',
    CARD_SELECTION: 'CARD_SELECTION',
    PIECE_SELECTION: 'PIECE_SELECTION'
};

export default PHASE;